#!/usr/bin/env bash
set -euo pipefail

IMAGE="${ANSIBLE_IMAGE:-particles/ansible:latest}"

[[ -t 0 ]] && TTY_FLAG="-it" || TTY_FLAG="-i"

docker run --rm ${TTY_FLAG} \
  -v "$(pwd)":/ansible \
  -v "${HOME}/.ssh":/root/.ssh:ro \
  -v "${HOME}/.ansible":/root/.ansible \
  --network host \
  "${IMAGE}" "$@"
