services:
  ansible:
    build: .
    image: particles/ansible:latest
    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh:ro
      - ~/.ansible:/root/.ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    network_mode: host
