---
- name: Test Ansible container
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Print hello
      ansible.builtin.debug:
        msg: "Ansible funziona! Versione: {{ ansible_version.full }}"

    - name: Mostra OS del container
      ansible.builtin.debug:
        msg: "Sistema: {{ ansible_os_family }} - {{ ansible_distribution }}"